"use strict";

// Flashcard generation (D17/D18) — turns the board's Notes artifact into first-class
// flashcard records in their own collection, each linking back to the shape it came
// from. This is the notes-only deck (shapes-only): a card's `sourceElementIds` are
// the board shapes the user can highlight (story 36).
//
//   const cards = createCardsGenerator({ gemini, userId });
//   const collection = await cards.generate({
//     notes,            // the D6 notes record (source of cards) — { boardId, lines }
//     boardId,          // stamped onto the collection + every card
//     deck,             // "notes" (this slice) | "document" (later) — default "notes"
//     elements,         // the board's Excalidraw elements (for arrows/bindings)
//     boardElementIds,  // ids of shapes still on the board (for reconcile retire)
//     prior,            // the prior cards collection, so schedules survive regenerate
//     userId,
//   });
//
// A card record (the spec shape, D18):
//   {
//     id,                        // stable id for React keys / reconcile bookkeeping
//     question, answer,
//     deck,                      // "notes" | "document"
//     boardId,
//     sourceElementIds,          // the board shapes it traces to (story 36)
//     reviewState,               // SM-2 schedule (ease/interval/dueDate/lapses/reps)
//   }
//
// The collection returned/persisted:
//   { boardId, deck, cards: [ ...card ] }
//
// TWO kinds of card come out of a board (D17):
//   1. Fact cards — one per note line, asking about that line's content. Generated by
//      the model FROM the verified notes (never from raw board text), so a card can
//      only ask about something already traced to the board.
//   2. Relationship cards — "what comes after X?" — built LOCALLY from the diagram's
//      arrows/bindings (buildRelationshipCards below), the kind of question a
//      text-only tool couldn't produce (story 37). These need no model call.
//
// VERIFICATION (D17). Every model-produced card passes the local key-terms gate
// (verify.js): its question must trace to the notes AND to at least one board shape,
// or it is dropped — never persisted (the required "drops un-traceable cards" test).
//
// REGENERATION (D18/story 40). New cards are matched to prior cards through the shared
// regeneration primitive (server/regeneration) by sourceElementIds + a question
// fingerprint. An unchanged card keeps its prior reviewState (its SM-2 schedule rides
// along); a card whose shapes were deleted retires; a genuinely new card starts on a
// fresh schedule. This module never inspects reviewState itself — reconcile carries
// the whole prior card forward and we lift its schedule onto the new card.
//
// All model access is through the central Gemini module (D2/D23); this module never
// touches the SDK, and a deferred ("working") result is awaited so a throttled call
// still yields cards (story 56). The client is stubbed in tests — no network, no model.

const { reconcile } = require("../regeneration");
const { freshSchedule } = require("./sm2");
const { verifyCard, cardSourceText } = require("./verify");
const { listSchema, parseList } = require("../gemini/jsonList");

const DEFAULT_DECK = "notes";

// Grounding fence appended to the card prompt: the notes are the only source, the
// output schema is fixed, nothing may be invented. Mirrors notes' SCHEMA_FENCE tone.
// The exact wording is server-side grounding and is never asserted in tests (tests
// assert on the RESULT); it must forbid inventing anything not in the notes.
const CARD_FENCE =
  "Write study flashcards from the notes below. Use ONLY these notes as source — " +
  "never add facts, terms, or topics not present in them. One card per distinct " +
  "point. Return ONLY JSON: an array of cards, each " +
  '{ "question": string, "answer": string, "sourceElementIds": string[] }. ' +
  "sourceElementIds MUST be copied from the note line the card is drawn from, so " +
  "each card links back to the shape it came from.";

// A stable-ish card id. Cards are matched across regenerations by content, not id, so
// the id only needs to be unique within a collection for React keys / bookkeeping.
function cardId(deck, seq) {
  return `${deck}-${seq}`;
}

// The fingerprint used to match a card to its prior self across a regenerate: its
// question, normalized (trimmed + lowercased). Two cards asking the same question of
// the same shapes are "the same card", so the prior one's schedule carries forward.
// Exposed for the reconcile call and for tests to reason about matching identically.
function questionFingerprint(card) {
  return String(card && card.question ? card.question : "").trim().toLowerCase();
}

// Parse the model's JSON into a raw card array. A malformed reply must not crash
// generation — it yields no model cards (degrade gracefully), same as empty notes.
// Accepts a bare array or an object wrapping a `cards` array (models vary).
// An unreadable reply throws rather than yielding [] — an empty deck reported as
// success spends a model call and tells the user nothing about why.
function parseCards(text) {
  return parseList(text, { key: "cards" });
}

// Normalize a raw model card into the card body (schedule + id are added later). A
// card with no question or answer text is dropped (returned null): a half-formed card
// isn't a study card. sourceElementIds defaults to [] and is filtered to strings so a
// formatting slip can't inject a non-string id.
function normalizeCard(raw, deck) {
  if (
    !raw ||
    typeof raw.question !== "string" ||
    !raw.question.trim() ||
    typeof raw.answer !== "string" ||
    !raw.answer.trim()
  ) {
    return null;
  }
  const ids = Array.isArray(raw.sourceElementIds)
    ? raw.sourceElementIds.filter((id) => typeof id === "string")
    : [];
  return {
    question: raw.question.trim(),
    answer: raw.answer.trim(),
    deck,
    sourceElementIds: ids,
  };
}

// Pull JSON text out of a central-module result. { status:"ok", response } now, or
// { status:"deferred", done } when throttled — await the working state so cards still
// come back on a busy moment (story 56). Mirrors notes' textOf so both seams read the
// module identically.
async function textOf(result) {
  const settled = result.status === "deferred" ? await result.done : result;
  const response = settled.response;
  return typeof response === "string" ? response : response?.text ?? "";
}

function buildRequest(userId, notes) {
  const source = cardSourceText(notes);
  return {
    userId,
    contents: [
      {
        role: "user",
        parts: [{ text: CARD_FENCE }, { text: `Notes:\n${source}` }],
      },
    ],
    config: {
      responseMimeType: "application/json",
      // Pin the envelope: a JSON mime type constrains that the reply IS json, not
      // its shape, and a reframed envelope parsed as "no cards".
      responseSchema: listSchema(
        {
          question: { type: "string" },
          answer: { type: "string" },
          sourceElementIds: { type: "array", items: { type: "string" } },
        },
        ["question", "answer"]
      ),
    },
  };
}

// --- relationship cards from the diagram (story 37) ------------------------------
//
// These are built LOCALLY from Excalidraw arrows/bindings — no model call — because
// "what comes after X?" is a question about the diagram's STRUCTURE, which a text-only
// tool can't see. An Excalidraw arrow binds a start element to an end element
// (startBinding.elementId -> endBinding.elementId); we read each such edge as
// "start leads to end" and turn it into a directional recall card. The card traces to
// BOTH endpoints and the arrow, so highlighting it lights up the whole relationship.

// Index shapes by id and pull a human label for a node (its text, or a bound label
// element's text). Excalidraw text lives either directly on a shape (`.text`) or in a
// separate text element bound via `containerId`; we cover the common cases and fall
// back to null (an unlabeled node can't make a readable question, so we skip its edge).
function labelIndex(elements) {
  const byId = new Map();
  for (const el of elements) if (el && el.id) byId.set(el.id, el);

  const containerText = new Map(); // containerId -> text of a bound label element
  for (const el of elements) {
    if (el && el.type === "text" && el.containerId && typeof el.text === "string") {
      containerText.set(el.containerId, el.text);
    }
  }

  function labelOf(id) {
    const el = byId.get(id);
    if (!el) return null;
    if (typeof el.text === "string" && el.text.trim()) return el.text.trim();
    const bound = containerText.get(id);
    return bound && bound.trim() ? bound.trim() : null;
  }

  return { byId, labelOf };
}

function buildRelationshipCards(elements, deck) {
  if (!Array.isArray(elements) || elements.length === 0) return [];
  const { labelOf } = labelIndex(elements);
  const cards = [];

  for (const el of elements) {
    if (!el || el.type !== "arrow") continue;
    const fromId = el.startBinding && el.startBinding.elementId;
    const toId = el.endBinding && el.endBinding.elementId;
    if (!fromId || !toId) continue; // a dangling arrow relates nothing

    const fromLabel = labelOf(fromId);
    const toLabel = labelOf(toId);
    if (!fromLabel || !toLabel) continue; // can't phrase a card without both labels

    cards.push({
      question: `In the diagram, what comes after "${fromLabel}"?`,
      answer: toLabel,
      deck,
      // Trace to both endpoints AND the arrow, so highlighting lights the relationship.
      sourceElementIds: [fromId, toId, el.id],
      // Marks the card's provenance for the client (a relationship card renders with a
      // diagram affordance); it rides along untouched through reconcile.
      relationship: true,
    });
  }

  return cards;
}

// A relationship card can't be verified against the notes prose (its wording is
// synthesized from shape labels, not copied from a note line), but it is inherently
// traceable — it is BUILT from real board shapes, so it always links back. We keep it
// as long as those shapes still exist on the board, which reconcile enforces via
// sourceElementIds. So relationship cards skip the notes key-terms gate.

function createCardsGenerator({ gemini, userId: defaultUserId } = {}) {
  if (!gemini || typeof gemini.generate !== "function") {
    throw new Error("createCardsGenerator: a central Gemini module is required");
  }

  async function generate({
    notes,
    boardId,
    deck = DEFAULT_DECK,
    elements = [],
    boardElementIds,
    prior,
    userId = defaultUserId,
  } = {}) {
    // Ask the model for fact cards from the verified notes, then keep only those that
    // trace back to the board (the D17 local key-terms gate). Empty notes → no model
    // cards, same as a malformed reply.
    const request = buildRequest(userId, notes);
    const result = await gemini.generate(request);
    const rawCards = parseCards(await textOf(result));
    const source = cardSourceText(notes);

    const factCards = [];
    for (const raw of rawCards) {
      const card = normalizeCard(raw, deck);
      if (!card) continue;
      if (!verifyCard(card, source)) continue; // un-traceable → drop (D17)
      factCards.push(card);
    }

    // Relationship cards come from the diagram structure, no model call (story 37).
    const relCards = buildRelationshipCards(elements, deck);

    const next = [...factCards, ...relCards];

    // Match each new card back to its prior self so review state survives regenerate
    // (story 40). boardElementIds defaults to every shape a next card traces to (a
    // first generation, or a caller that doesn't pass the live board, treats all
    // referenced shapes as present — nothing to retire yet).
    const onBoard =
      boardElementIds ||
      [...new Set(next.flatMap((c) => c.sourceElementIds))];

    const { items } = reconcile({
      prior: Array.isArray(prior) ? prior : prior && prior.cards ? prior.cards : [],
      next,
      boardElementIds: onBoard,
      fingerprint: questionFingerprint,
    });

    // Assemble the persisted cards in next order, lifting the prior schedule onto an
    // unchanged card and starting a fresh one otherwise. reconcile hands back the
    // whole prior card, so we read its reviewState without the primitive ever
    // knowing what a schedule is.
    const cards = items.map((entry, i) => {
      const body = entry.next;
      const reviewState =
        entry.status === "unchanged" && entry.prior && entry.prior.reviewState
          ? entry.prior.reviewState
          : freshSchedule();
      const id = entry.prior && entry.prior.id ? entry.prior.id : cardId(deck, i);
      return { id, boardId, ...body, reviewState };
    });

    return { boardId, deck, cards };
  }

  return { generate };
}

// Production wiring: build a cards generator from a central Gemini module. Returns
// null when no Gemini module is configured so the feature degrades gracefully
// (mirrors createNotesFromGemini) rather than crashing the server at boot.
function createCardsFromGemini(gemini) {
  if (!gemini) return null;
  return createCardsGenerator({ gemini });
}

module.exports = {
  createCardsGenerator,
  createCardsFromGemini,
  questionFingerprint,
  buildRelationshipCards,
  DEFAULT_DECK,
};
